# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='uploadImages', verbose_name='图片')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
        ),
    ]
